"""A script to take sphinx build files and set up a github pages website.

Github pages looks for an index.html in either the root directory or a
"root/docs/" directory of a specified branch. This script copies the build
files generated by sphinx's `make html` command in the sphinx directory to the
docs directory used by github pages to host the website.

Assumes the following project directory structure

gh_pages (main git branch)
|
|_ docs/
|
|_ sphinx/
     |
     |_ build/
     |    |
     |    |_html/
     |
     |_ make_gh_pages.py
"""

from os.path import dirname, abspath
from shutil import copytree, rmtree

sphinx_dir = dirname(abspath(__file__))
gh_pages_docs_dir = dirname(sphinx_dir) + '/docs/'
sphinx_build_dir = sphinx_dir + "/build/html/"
rmtree(gh_pages_docs_dir, ignore_errors=True)
copytree(sphinx_build_dir, gh_pages_docs_dir)

# Add a `.nojekyll` file to signal this is not a jekyll project.
open(gh_pages_docs_dir + '.nojekyll', 'a').close()
